stages:
  - all
#  - build

test:
  stage: all
  image: goland
  script:
    - go test . 
  rules:
      - if: '$CI_DEFAULT_BRANCH'
#    - changes:
#      - /*.go
#  script:
#   - go test .

build:
  stage: all
  image: docker:latest
  script:
   - docker build .

