stages:
  - all
#  - build

test:
  stage: all
  image: goland
  rules:
    - if: '$CI_DEFAULT_BRANCH'
#    - changes:
#      - /*.go
  script:
   - go test .

build:
  stage: all
  image: docker:latest
  script:
   - docker build .

